version: '3.3'
services:
  server:
    build: .
    ports:
      - '5001:5000'
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: